### ISSUE TITLE
Dockerized image taking too much space

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-frontend#5]
Dockerized image seems to take too much space: 796.56 MB as reported by dockerhub. Built locally (see instructions) and using `docker image ls` its 2GB.

Reduce the space it consumes to something more reasonable.

**Comment by weboko** [comment]
This PR https://github.com/waku-org/waku-frontend/pull/7 should reduce used space by not copying / downloading `node_modules` in image. 
After this image is `1.11GB` for me and there is a limit we can go since only `FROM node:18` takes `1.09GB`.
